export default [
        {
          id: 1,
          description: "Tried making homemade pizza for the first time, and it turned out amazing! Cooking is such a fun and relaxing activity.",
          description_de: "Ich habe zum ersten Mal versucht, eine hausgemachte Pizza zu machen, und sie ist fantastisch geworden! Kochen ist eine so unterhaltsame und entspannende Aktivität.",
          date: "2 hours ago",
          likes: 120,
          comments: 24,
          image: "https://picsum.photos/1080/607?random=1",
          user: {
            name: "John Carter",
            avatar: "https://randomuser.me/api/portraits/men/1.jpg",
          },
        },
        {
          id: 2,
          description: "Spent the day at the beach with my friends. The waves were calming, and the sunset was breathtaking!",
          description_de: "Ich habe den Nachmittag mit meinen Freunden am Strand verbracht. Die Wellen waren so beruhigend und der Sonnenuntergang einfach atemberaubend!",
          date: "6 hours ago",
          likes: 200,
          comments: 40,
          image: "https://picsum.photos/1080/607?random=2",
          user: {
            name: "Emily Johnson",
            avatar: "https://randomuser.me/api/portraits/women/2.jpg",
          },
        },
        {
          id: 3,
          description: "Had a productive day working on a project. Solved a tricky bug. Now everything runs smoothly!",
          description_de: "Ich hatte einen produktiven Tag mit einem Programmierprojekt. Ich habe einen kniffligen Fehler gelöst. Jetzt läuft alles reibungslos!",
          date: "2 days ago",
          likes: 95,
          comments: 15,
          image: "https://picsum.photos/1080/607?random=3",
          user: {
            name: "David Smith",
            avatar: "https://randomuser.me/api/portraits/men/3.jpg",
          },
        },
        {
          id: 4,
          description: "Today was a fantastic day! I woke up early, enjoyed the sunrise, and had a peaceful morning walk. Later, I treated myself to a delicious coffee and finished reading an amazing book.",
          description_de: "Heute war ein fantastischer Tag! Ich bin früh aufgewacht, habe den Sonnenaufgang genossen und einen friedlichen Morgenspaziergang gemacht. Später habe ich mich mit einem köstlichen Kaffee belohnt und ein tolles Buch fertig gelesen.",
          date: "February 14",
          likes: 180,
          comments: 28,
          image: "https://picsum.photos/1080/607?random=4",
          user: {
            name: "Sophia Williams",
            avatar: "https://randomuser.me/api/portraits/women/4.jpg",
          },
        },
        {
          id: 5,
          description: "Hiked up a mountain today. The view from the top was incredible. Nature is truly refreshing for the soul.",
          description_de: "Ich bin heute auf einen Berg gewandert und die Aussicht von oben war unglaublich. Die Natur ist wirklich erfrischend für die Seele.",
          date: "February 10",
          likes: 230,
          comments: 50,
          image: "https://picsum.photos/1080/607?random=5",
          user: {
            name: "James Brown",
            avatar: "https://randomuser.me/api/portraits/men/5.jpg",
          },
        },
          {
            id: 6,
            description: "Spent the whole day painting. Creating art is such a beautiful way to express emotions.",
            description_de: "Den ganzen Tag gemalt. Kunst zu schaffen ist eine wunderschöne Möglichkeit, Emotionen auszudrücken.",
            date: "February 7",
            likes: 170,
            comments: 32,
            image: "https://picsum.photos/1080/607?random=6",
            user: {
              name: "Olivia Taylor",
              avatar: "https://randomuser.me/api/portraits/women/6.jpg",
            },
          },
          {
            id: 7,
            description: "Watched an old classic movie today. Sometimes, the simplest things bring the most joy.",
            description_de: "Heute einen alten Klassiker angeschaut. Manchmal bringen die einfachsten Dinge die größte Freude.",
            date: "January 30",
            likes: 140,
            comments: 18,
            image: "https://picsum.photos/1080/607?random=7",
            user: {
              name: "Michael Anderson",
              avatar: "https://randomuser.me/api/portraits/men/7.jpg",
            },
          },
          {
            id: 8,
            description: "Had an amazing dinner with family at the beach. There's nothing better than delicious food and great company!",
            description_de: "Ein tolles Abendessen mit der Familie gehabt. Es gibt nichts Besseres als gutes Essen und großartige Gesellschaft!",
            date: "December 25, 2024",
            likes: 195,
            comments: 35,
            image: "https://picsum.photos/1080/607?random=8",
            user: {
              name: "Emma Martinez",
              avatar: "https://randomuser.me/api/portraits/women/8.jpg",
            },
          },
          {
            id: 9,
            description: "Visited a local bookstore and discovered some incredible new reads. Can't wait to dive into them!",
            description_de: "Eine lokale Buchhandlung besucht und einige fantastische neue Bücher entdeckt. Ich kann es kaum erwarten, sie zu lesen!",
            date: "December 29, 2024",
            likes: 110,
            comments: 22,
            image: "https://picsum.photos/1080/607?random=9",
            user: {
              name: "Daniel White",
              avatar: "https://randomuser.me/api/portraits/men/9.jpg",
            },
          },
          {
            id: 10,
            description: "Practiced yoga for an hour today, feeling so relaxed and refreshed!",
            description_de: "Heute eine Stunde Yoga praktiziert und fühle mich so entspannt und erfrischt!",
            date: "December 21, 2024",
            likes: 125,
            comments: 19,
            image: "https://picsum.photos/1080/607?random=10",
            user: {
              name: "Ava Clark",
              avatar: "https://randomuser.me/api/portraits/women/10.jpg",
            },
          },
          {
            id: 11,
            description: "Baked some chocolate chip cookies and they were delicious! My house smells amazing now.",
            description_de: "Einige Schokoladenkekse gebacken, und sie waren köstlich! Mein Haus riecht jetzt fantastisch.",
            date: "December 22, 2024",
            likes: 185,
            comments: 27,
            image: "https://picsum.photos/1080/607?random=11",
            user: {
              name: "William Harris",
              avatar: "https://randomuser.me/api/portraits/men/11.jpg",
            },
          },
          {
            id: 12,
            description: "Had a great workout at the gym today! Feeling stronger every day.",
            description_de: "Heute ein tolles Workout im Fitnessstudio gemacht! Ich fühle mich jeden Tag stärker.",
            date: "December 30, 2024",
            likes: 160,
            comments: 25,
            image: "https://picsum.photos/1080/607?random=12",
            user: {
              name: "Isabella Nelson",
              avatar: "https://randomuser.me/api/portraits/women/12.jpg",
            },
          },
          {
            id: 13,
            description: "Played guitar and learned a new song today. Music is truly magical!",
            description_de: "Heute Gitarre gespielt und ein neues Lied gelernt. Musik ist wirklich magisch!",
            date: "December 31, 2024",
            likes: 145,
            comments: 20,
            image: "https://picsum.photos/1080/607?random=13",
            user: {
              name: "Mason Wilson",
              avatar: "https://randomuser.me/api/portraits/men/13.jpg",
            },
          },
          {
            id: 14,
            description: "Visited a beautiful garden today and took so many photos. Nature is breathtaking!",
            description_de: "Heute einen wunderschönen Garten besucht und viele Fotos gemacht. Die Natur ist atemberaubend!",
            date: "November 25, 2024",
            likes: 210,
            comments: 38,
            image: "https://picsum.photos/1080/607?random=14",
            user: {
              name: "Mia Robinson",
              avatar: "https://randomuser.me/api/portraits/women/14.jpg",
            },
          },
          {
            id: 15,
            description: "Had a relaxing evening watching the stars. The sky was so clear and peaceful.",
            description_de: "Einen entspannten Abend damit verbracht, die Sterne zu beobachten. Der Himmel war so klar und friedlich.",
            date: "November 16, 2024",
            likes: 180,
            comments: 31,
            image: "https://picsum.photos/1080/607?random=15",
            user: {
              name: "Ethan Walker",
              avatar: "https://randomuser.me/api/portraits/men/15.jpg",
            },
          },
          {
            id: 16,
            description: "Enjoyed a snowy day with hot cocoa and a good book. Winter is magical!",
            description_de: "Einen verschneiten Tag mit heißem Kakao und einem guten Buch genossen. Der Winter ist magisch!",
            date: "November 12, 2024",
            likes: 210,
            comments: 45,
            image: "https://picsum.photos/1080/607?random=16",
            user: {
              name: "Sophia Green",
              avatar: "https://randomuser.me/api/portraits/women/16.jpg",
            },
          },
          {
            id: 17,
            description: "Went on a road trip and discovered some hidden gems. Adventure is out there!",
            description_de: "Eine Autoreise gemacht und einige versteckte Juwelen entdeckt. Das Abenteuer ruft!",
            date: "November 10, 2024",
            likes: 190,
            comments: 37,
            image: "https://picsum.photos/1080/607?random=17",
            user: {
              name: "Liam Scott",
              avatar: "https://randomuser.me/api/portraits/men/17.jpg",
            },
          },
          {
            id: 18,
            description: "Tried a new restaurant and the food was amazing. I love exploring different cuisines!",
            description_de: "Ein neues Restaurant ausprobiert und das Essen war unglaublich. Ich liebe es, verschiedene Küchen zu erkunden!",
            date: "November 5, 2024",
            likes: 180,
            comments: 28,
            image: "https://picsum.photos/1080/607?random=18",
            user: {
              name: "Hannah Lee",
              avatar: "https://randomuser.me/api/portraits/women/18.jpg",
            },
          },
      
  ];
  